export const routes = {
  home: "/",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  library: "/library",
  libraryUpload: "/library/upload",
  libraryDetail: (id: string) => `/library/${id}`,
  chat: "/chat",
  chatConversation: (id: string) => `/chat/${id}`,
  study: "/study",
  studyDeck: (documentId: string) => `/study/${documentId}`,
  studyQuiz: (documentId: string, chapterKey: string) =>
    `/study/${documentId}/quiz/${encodeURIComponent(chapterKey)}`,
  questionBank: "/question-bank",
  questionBankDetail: (documentId: string) => `/question-bank/${documentId}`,
  questionBankQuiz: (documentId: string) => `/question-bank/${documentId}/quiz`,
  notifications: "/notifications",
  settings: "/settings",
} as const;
